name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "43 7 * * 0"
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install prerequisites
        run: "sudo apt-get install -y build-essential automake autoconf flex check llvm-dev pkg-config zlib1g-dev libdw-dev libffi-dev"
      - name: Setup bazel
        uses: abhinavsingh/setup-bazel@v3
        with:
          version: 5.4.0
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: "bazel build //..."

